### ISSUE TITLE
System.HttpResponse[Status=Unsupported Media Type, StatusCode=415]

### ISSUE THREAD

**Issue by atulrajguru9** [natewallace/ApexNTLM#3]
When we send HTTP request we get error saying that Unsupported Media Type. This means that the content we are sending is not understood by server  and so server is saying media(Content) not supported. 
![ntlm](https://cloud.githubusercontent.com/assets/10432798/9727075/73b87018-5618-11e5-9e0c-8ce075fa5db4.jpg)

**Comment by natewallace** [comment]
The HttpClient class creates copies of the HttpRequest object to send to the server.  Unfortunately there is no way to read the header values out of an HttpRequest instance unless you know the keys ahead of time so the HttpClient class can't copy them over.  This means if you are setting headers on your HttpRequest such as Content-Type they will not be sent to the server.

I'm guessing this is why you are getting a 415 error.  I will look at updating the interface to allow headers to be specified with the request.

**Comment by atulrajguru9** [comment]
Thank you for your reply Nate. 
You are exactly Right. I think there are 3 ways to handle this issue.

1) We can check if specific header is set and then clone it for ex.

if(request.getHeader('Content-Type').length() > 0 ){
        req.setHeader('Content-Type',request.getHeader('Content-Type'));
}       

2) We can prepare list of headers and check which are set and then copy them.

3) we can add additional parameters to clone method that will allow user to pass list of headers. Then we can use this list in clone method. 

Let me know your views.

Thank you,
Atul

**Comment by natewallace** [comment]
I think number 3 is the way to go as it's the most flexible.  I've update the HttpClient class with a new send method that accepts a map of headers that is passed to the server with the request.

**Comment by atulrajguru9** [comment]
Thank you. That looks great!

**Comment by dseligson** [comment]
Why not add the "headers Map initialization" to your httpClient constructor, and save as a Map there?
This way, you don't need all the special code in your "send" method.

**Comment by dseligson** [comment]
I want to thank you for putting this astonishingly complex Http wrapper together.  It's awesome.  All it needed was 2 minor bug fixes and setting the Content-type to 'text/html', and it worked like a champ.  
Thanks very much.

**Comment by natewallace** [comment]
I didn't put the headers in the constructor because I wanted to mimic the built in http client as much as possible.  In this way you can use the same client to send multiple requests with different headers if needed.  

Also, the only reason you need to pass in the headers as an argument is because SalesForce doesn't expose a way to query them on the request object otherwise I would grab them from there.

**Comment by dseligson** [comment]
That makes sense.  I didn't realize there was no HttpRequest.getHeaders() method.  Salesforce always manages to get their functionality to about 75% of what's needed.  
Still, though, the elegance -- no, the "beauty" of your integration is that I can use it entirely and only change one line in my API code (where the instantiation of the Http client is done).
If you just added a "getHeader('ContentType');" call when you're cloning the request, however, you'll have not changed the specification of the http client, and your integration will then work for about 90% (guess, of course) for all uses.  Otherwise, the integration is pretty much guaranteed to return a 405 until the developer realizes the request headers need to be otherwise initialized.

Just a suggestion, either way, I'm using your code.  It's a nice piece of work.

**Comment by sylvain-priser** [comment]
[SOLVED]
Hi @natewallace , thank you for sharing this code !

I'm very close to get my test working but I'm still struggling with HTTP 415 Error when trying to send a POST request. I tried to debug but I can't find where could be the issue. I only see that Authentication headers are not identical between my test on SOAP-UI and my APEX code..

Here is a log if you have the opportunity to have a look at it :
[apex-07L1700000MtOktEAF.log](https://github.com/natewallace/ApexNTLM/files/3509014/apex-07L1700000MtOktEAF.log)

I will continue searching..

Edit : OK I just understood how to use Header map ! It works fine !!

**Comment by Rajesh609** [comment]
Hi @sylvain-priser ,Could you plz let me know how to pass the headers , I am getting same HTTP 415 error when sending request from salesforce.

**Comment by sylvain-priser** [comment]
Hi Rajesh,

here is an extract of my code where headers are set : 

`
private void SOAPCallout(String wsPage, String wsSOAPAction, DOM.Document wsRequestDoc){        		
 
	Map<string, string> wsHeaders = new Map<String, String>();

        wsHeaders.put('SOAPAction', wsSOAPAction);
        wsHeaders.put('Content-Type', soapContentType);

        HttpRequest wsRequest = new HttpRequest();
		
	wsRequest.setEndpoint(navEndpoint + wsPage);
        wsRequest.setMethod(soapMethod);
        wsRequest.setBody(wsRequestDoc.toXmlString());

	System.debug('Request.Body : ' + wsRequestDoc.toXmlString());

	HttpClient wsClient = new HttpClient(navDomain + '\\' + navUsername, navPassword);
        HTTPResponse wsResponse = wsClient.send(wsRequest, wsHeaders);

	navResponseHttpStatus = wsResponse.getStatusCode();	
	system.debug('Response.HttpStatus : ' + navResponseHttpStatus);	

	if (navResponseHttpStatus == 200)
	{
		// Get response content as Blob
		navResponseBlob = wsResponse.getBodyAsBlob();		
		// Get response content as Document		
		navResponseDoc = wsResponse.getBodyDocument();		
	}	
}
`
